# Generated by Django 4.2.6 on 2023-12-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(blank=True),
        ),
    ]
