# Generated by Django 4.2.6 on 2024-01-21 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_card', '0003_class_inventoryitem_profession_race_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='CharacterClass',
        ),
    ]
