# Generated by Django 4.2.6 on 2024-01-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_card', '0004_rename_class_characterclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficiencies',
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.RemoveField(
            model_name='character',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spells',
        ),
        migrations.AddField(
            model_name='characterclass',
            name='spells',
            field=models.ManyToManyField(related_name='classes', to='character_card.spell'),
        ),
    ]
