# Generated by Django 4.2.6 on 2024-01-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_card', '0005_spell_remove_character_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character_card.characterclass'),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.ManyToManyField(blank=True, to='character_card.inventoryitem'),
        ),
        migrations.AddField(
            model_name='character',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character_card.profession'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character_card.race'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(blank=True, to='character_card.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, to='character_card.spell'),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
