# Generated by Django 4.2.6 on 2024-01-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_card', '0006_character_character_class_character_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='class_name',
            field=models.CharField(default='DefaultClassName', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory_items',
            field=models.ManyToManyField(related_name='characters_for_inventory_items', to='character_card.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='character',
            name='inventory',
            field=models.ManyToManyField(related_name='characters_for_inventory', to='character_card.inventoryitem'),
        ),
    ]
