# Generated by Django 4.2.6 on 2024-01-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_card', '0007_character_class_name_character_inventory_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='learned',
            field=models.BooleanField(default=False),
        ),
    ]
