from django.contrib.auth.models import User
from django.db import models

class Character(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.TextField()
    race = models.TextField()
    class_name = models.TextField(db_column='class')
    level = models.IntegerField()
    strength = models.IntegerField()
    dexterity = models.IntegerField()
    constitution = models.IntegerField()
    intelligence = models.IntegerField()
    wisdom = models.IntegerField()
    charisma = models.IntegerField()
    StrST = models.IntegerField()
    DexST = models.IntegerField()
    ConST = models.IntegerField()
    IntST = models.IntegerField()
    WisST = models.IntegerField()
    Mhitdice = models.IntegerField()
    Chitdice = models.IntegerField()
    Dsp = models.IntegerField()
    Dsf = models.IntegerField()
    skills = models.TextField()
    proficiencies = models.TextField()
    spells = models.TextField()
    inventory = models.TextField()